name: macOS Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    # Re-enable when macos-26 is no longer in preview
    # See: https://github.com/actions/runner-images
    # runs-on: macos-latest
    runs-on: macos-26
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Create build directory
        run: mkdir -p build

      - name: Import Developer ID Certificate
        run: |
          echo "${{ secrets.DEVELOPER_ID_P12 }}" | base64 --decode > build/DeveloperID.p12
          security create-keychain -p "" build.keychain
          security import build/DeveloperID.p12 -k build.keychain -P "${{ secrets.DEVELOPER_ID_P12_PASSWORD }}" -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings -t 3600 -l build.keychain

      - name: Configure keychain for codesign
        run: |
          security set-key-partition-list -S apple-tool:,apple: -k "" build.keychain

      - name: Install Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.JIRAIYA_PROVISIONING_PROFILE }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/Jiraiya.provisionprofile

      - name: Build and Archive App
        run: |
          set -o pipefail
          xcodebuild -project "Jiraiya/Jiraiya.xcodeproj" \
            -scheme "Jiraiya" \
            -configuration Release \
            -archivePath "$PWD/build/Jiraiya.xcarchive" \
            -destination "platform=macOS,arch=arm64" \
            ARCHS=arm64 ONLY_ACTIVE_ARCH=YES \
            DEBUG_INFORMATION_FORMAT="dwarf" \
            ENABLE_HARDENED_RUNTIME=YES \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="${{ secrets.APPLE_TEAM_ID }}" \
            CODE_SIGN_IDENTITY="Developer ID Application: Victor Noagbodji (2DZ6D8C78T)" \
            archive

      - name: Export App
        run: |
          xcodebuild -exportArchive \
            -archivePath "$PWD/build/Jiraiya.xcarchive" \
            -exportOptionsPlist "$PWD/Jiraiya/Jiraiya/ExportOptions.plist" \
            -exportPath "$PWD/build"

      - name: Notarize app
        run: |
          ditto -c -k --keepParent "build/Jiraiya.app" "build/Jiraiya.zip"
          xcrun notarytool submit "build/Jiraiya.zip" \
            --apple-id "${{ secrets.APPLE_ID }}" \
            --team-id "${{ secrets.APPLE_TEAM_ID }}" \
            --password "${{ secrets.APP_SPECIFIC_PASSWORD }}" \
            --wait
          xcrun stapler staple "build/Jiraiya.app"

      - name: Create DMG
        run: |
          hdiutil create -volname "Jiraiya" \
            -srcfolder "build/Jiraiya.app" \
            -ov -format UDZO "build/Jiraiya.dmg"

      - name: Upload DMG to Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/Jiraiya.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
